# This file contains the fastlane.tools configuration
# You can find the documentation at https://docs.fastlane.tools
#
# For a list of all available actions, check out
#
#     https://docs.fastlane.tools/actions
#
# For a list of all available plugins, check out
#
#     https://docs.fastlane.tools/plugins/available-plugins
#

# Uncomment the line if you want fastlane to automatically update itself
# update_fastlane

default_platform(:ios)

platform :ios do

  desc "Runs all the tests"
  lane :test do
    # Run Swift tests 
    # https://docs.fastlane.tools/getting-started/ios/running-tests/
    run_tests(scheme: "HelloiOSWorld")
  end

  desc "Build the app"
  lane :build do
    # Assign app
    # https://docs.fastlane.tools/codesigning/getting-started/#using-cert-and-sigh
    get_certificates           # invokes cert
    get_provisioning_profile   # invokes sigh
    # As best practice
    # Increment build number.
    # https://docs.fastlane.tools/getting-started/ios/beta-deployment/#best-practices
    # Requires XCodeProj configuration
    # https://developer.apple.com/library/archive/qa/qa1827/_index.html
    increment_build_number
    build_app
  end

  desc "Upload to Crashlytics"
  lane :fabric do
    # Upload app to Fabric Beta (Crashlytics)
    # https://docs.fastlane.tools/getting-started/ios/beta-deployment/#beta-testing-services
    # Should be configured with Fabric and Crashlytics Pods
    # Install instructions at
    # https://fabric.io/kits/ios/crashlytics/install
    crashlytics
  end

  desc "Push a new beta build to TestFlight"
  lane :beta do
    # Upload app to Test Flight
    # https://docs.fastlane.tools/getting-started/ios/beta-deployment/#uploading-your-app
    upload_to_testflight
  end
end
